name: Deploy Playground to GitHub Pages

on:
  push:
    branches: [dev, master, main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v4

      - name: Install Node.js 🟢
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies 🛠️
        run: pnpm install

      - name: Build App 🏗️
        run: pnpm run build:app

      - name: Add .nojekyll 📄
        run: touch dist-app/.nojekyll

      - name: Set Deployment Folder 📁
        id: folder
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "target=." >> $GITHUB_OUTPUT
            echo "exclude=[]" >> $GITHUB_OUTPUT
          else
            echo "target=dev" >> $GITHUB_OUTPUT
            echo "exclude=[]" >> $GITHUB_OUTPUT
          fi

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist-app
          branch: gh-pages
          target-folder: ${{ steps.folder.outputs.target }}
          clean: false # Important: prevents dev and master from deleting each other
